### ISSUE TITLE
PRACTICA #7 DE HILOS 

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/practica-final-de-hilos-equipo-m-a-r-topicos-a-p#2]
Archivo practica #7
[Hilos7.zip](https://github.com/SistemasTecTlaxiaco/practica-final-de-hilos-equipo-m-a-r-topicos-a-p/files/8608812/Hilos7.zip)
[Practica # 7 Hilos.pdf](https://github.com/SistemasTecTlaxiaco/practica-final-de-hilos-equipo-m-a-r-topicos-a-p/files/8628839/Practica.7.Hilos.pdf)

**Comment by EvelynLopezz** [comment]
Calificación de la practica solamente de los alumnos MAGALY NICOLAS SANCHEZ, RAEL GABRIEL GARCIA, ADOLFO GERMAN VÁSQUEZ ROJAS:
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
